package za.co.swingy.view.gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;
import lombok.Setter;
import za.co.swingy.controller.EncounterController;
import za.co.swingy.controller.GameController;
import za.co.swingy.model.items.Armor;
import za.co.swingy.model.items.Helm;
import za.co.swingy.model.items.Weapon;
import za.co.swingy.view.EncounterView;

import javax.swing.*;
import javax.validation.constraints.NotNull;
import java.awt.*;

@Getter
@Setter
public class EncounterGuiView extends FrameView implements EncounterView {
	@NotNull
	private EncounterController controller;
	@NotNull
	public GameController			gameController;
	private JPanel panel1;
	private JPanel mainPanel;
	private JPanel encounterPanel;
	private JPanel heroPanel;
	private JTextArea nameTextArea;
	private JTextArea classTextArea;
	private JTextArea levelTextArea;
	private JTextArea hpTextArea;
	private JTextArea attTextArea;
	private JTextArea defTextArea;
	private JPanel enemyPanel;
	private JLabel enemyNameLabel;
	private JTextArea enemyNameTextArea;
	private JLabel enemyClassLabel;
	private JTextArea enemyClassTextArea;
	private JLabel enemyLevelLabel;
	private JTextArea enemyLavalTextArea;
	private JLabel enemyHPLabel;
	private JLabel enemyAttLabel;
	private JLabel enemyDefLabel;
	private JTextArea enemyHPTextArea;
	private JTextArea enemyAttTextArea;
	private JTextArea enemyDefTextArea;
	private JTextPane enemyStatsTextPane;
	private JTextPane heroStatsTestPane;
	private JTextArea youHave3ChoicesTextArea;
	private JButton fightButton;
	private JButton simulateButton;
	private JButton runButton;
	private JButton switchButton;

	public EncounterGuiView(GameController controller) {
		this.gameController = controller;
	}

	public void					display() {

	}

	public void					runFailed() {

	}

	public void					battleHistory() {

	}

	public void					itemDrop(String item, int index) {

	}

	public void					armorDrop(Armor armor) {

	}

	public void					weaponDrop(Weapon weapon) {

	}

	public void					helmDrop(Helm helm) {

	}

	public void					success() {

	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
	}
}
