package za.co.swingy.view.gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import za.co.swingy.controller.GameController;
import za.co.swingy.view.MapView;

import javax.swing.*;
import java.awt.*;

public class MapGuiView implements MapView {
	public void displayMap(char[][] map, int mapSize) {

	}

	public int display(GameController controller) {
		return 0;
	}

	public void death() {
	}

	public void runAway() {
	}

	public void success() {
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
	}
}
